/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2020-01-02 06:56:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <title>체크아웃</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("        <div class=\"cart-table-area section-padding-100\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12 col-lg-8\">\r\n");
      out.write("                        <div class=\"checkout_details_area mt-50 clearfix\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"cart-title\">\r\n");
      out.write("                                <h2>Checkout</h2>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <form action=\"#\" method=\"post\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"first_name\" value=\"\" placeholder=\"First Name\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"last_name\" value=\"\" placeholder=\"Last Name\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"company\" placeholder=\"Company Name\" value=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                                        <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Email\" value=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                                        <select class=\"w-100\" id=\"country\">\r\n");
      out.write("                                        <option value=\"usa\">United States</option>\r\n");
      out.write("                                        <option value=\"uk\">United Kingdom</option>\r\n");
      out.write("                                        <option value=\"ger\">Germany</option>\r\n");
      out.write("                                        <option value=\"fra\">France</option>\r\n");
      out.write("                                        <option value=\"ind\">India</option>\r\n");
      out.write("                                        <option value=\"aus\">Australia</option>\r\n");
      out.write("                                        <option value=\"bra\">Brazil</option>\r\n");
      out.write("                                        <option value=\"cana\">Canada</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control mb-3\" id=\"street_address\" placeholder=\"Address\" value=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"city\" placeholder=\"Town\" value=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" id=\"zipCode\" placeholder=\"Zip Code\" value=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                                        <input type=\"number\" class=\"form-control\" id=\"phone_number\" min=\"0\" placeholder=\"Phone No\" value=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12 mb-3\">\r\n");
      out.write("                                        <textarea name=\"comment\" class=\"form-control w-100\" id=\"comment\" cols=\"30\" rows=\"10\" placeholder=\"Leave a comment about your order\"></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <div class=\"custom-control custom-checkbox d-block mb-2\">\r\n");
      out.write("                                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck2\">\r\n");
      out.write("                                            <label class=\"custom-control-label\" for=\"customCheck2\">Create an accout</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"custom-control custom-checkbox d-block\">\r\n");
      out.write("                                            <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck3\">\r\n");
      out.write("                                            <label class=\"custom-control-label\" for=\"customCheck3\">Ship to a different address</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                        <div class=\"cart-summary\">\r\n");
      out.write("                            <h5>Cart Total</h5>\r\n");
      out.write("                            <ul class=\"summary-table\">\r\n");
      out.write("                                <li><span>subtotal:</span> <span>$140.00</span></li>\r\n");
      out.write("                                <li><span>delivery:</span> <span>Free</span></li>\r\n");
      out.write("                                <li><span>total:</span> <span>$140.00</span></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"payment-method\">\r\n");
      out.write("                                <!-- Cash on delivery -->\r\n");
      out.write("                                <div class=\"custom-control custom-checkbox mr-sm-2\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"custom-control-input\" id=\"cod\" checked>\r\n");
      out.write("                                    <label class=\"custom-control-label\" for=\"cod\">Cash on Delivery</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Paypal -->\r\n");
      out.write("                                <div class=\"custom-control custom-checkbox mr-sm-2\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"custom-control-input\" id=\"paypal\">\r\n");
      out.write("                                    <label class=\"custom-control-label\" for=\"paypal\">Paypal <img class=\"ml-15\" src=\"img/core-img/paypal.png\" alt=\"\"></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"cart-btn mt-100\">\r\n");
      out.write("                                <a href=\"#\" class=\"btn amado-btn w-100\">Checkout</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
