/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2020-01-02 06:55:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>안녕하세요</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".animation_canvas { /* 이미지 한개의 영역만 보여줌 */\r\n");
      out.write("\toverflow: hidden; /* 영역 외부의 내용을 보여주지 않음 */\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\twidth: 1583px;\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("}\r\n");
      out.write("/* 이미지 5개가 보여지는 영역  */\r\n");
      out.write(".slider_panel {\r\n");
      out.write("\twidth: 7915px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("/* 이미지 한개 보여지는 영역  */\r\n");
      out.write(".slider_image {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 1583px;\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("}\r\n");
      out.write("/* 설명을 보여주는 영역*/\r\n");
      out.write(".slider_text_panel {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 100px;\r\n");
      out.write("\tleft: 50px;\r\n");
      out.write("}\r\n");
      out.write("/* 설명의 내용 */\r\n");
      out.write(".slider_text {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("}\r\n");
      out.write("/* 선택버튼의 영역*/\r\n");
      out.write(".control_panel {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 380px;\r\n");
      out.write("\tleft: 791px;\r\n");
      out.write("\theight: 13px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("/*선택버튼 이미지 */\r\n");
      out.write(".control_button {\r\n");
      out.write("\twidth: 12px;\r\n");
      out.write("\theight: 46px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground: url('../slide/point_button.png');\r\n");
      out.write("}\r\n");
      out.write("/* 마우스가 올라가게 되면  살짝 올라감*/\r\n");
      out.write(".control_button:hover {\r\n");
      out.write("\ttop: -16px;\r\n");
      out.write("}\r\n");
      out.write("/* 다시 돌아옴*/\r\n");
      out.write(".control_button.select {\r\n");
      out.write("\ttop: -31px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t//버튼들 이벤트 등록\r\n");
      out.write("\t\t$(\".control_button\").each(function(index) {\r\n");
      out.write("\t\t\t$(this).attr(\"idx\", index)\r\n");
      out.write("\t\t}).click(function() {\r\n");
      out.write("\t\t\t//$(this).attr('idx') : 클릭된 컴포넌트의 idx 속성 값 0~4\r\n");
      out.write("\t\t\tvar index = $(this).attr('idx');\r\n");
      out.write("\t\t\tmoveSlider(index);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//클릭과 상관없이 화면이 로드 된 경우 실행됨\r\n");
      out.write("\t\t//처음에 몰아나오는 텍스트를 보이지 않도록 설정 + idx 속성 등록\r\n");
      out.write("\t\t$('.slider_text').css(\"left\", -300).each(function(index) {\r\n");
      out.write("\t\t\t$(this).attr(\"idx\", index)\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tmoveSlider(0); //첫번째 이미지가 화면에 출력되도록\r\n");
      out.write("\t\tvar idx = 0;\r\n");
      out.write("\t\tvar inc = 1;\r\n");
      out.write("\t\tsetInterval(function() {\r\n");
      out.write("\t\t\tif (idx >= 4) {\r\n");
      out.write("\t\t\t\tinc = -1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (idx <= 0) {\r\n");
      out.write("\t\t\t\tinc = 1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tidx += inc;\r\n");
      out.write("\t\t\tmoveSlider(idx);\r\n");
      out.write("\t\t}, 5000);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction moveSlider(index) {\r\n");
      out.write("\t\tvar moveLeft = -(index * 1583);\r\n");
      out.write("\t\t$('.slider_panel').animate({\r\n");
      out.write("\t\t\tleft : moveLeft\r\n");
      out.write("\t\t}, 'slow');\r\n");
      out.write("\t\t$('.control_button[idx=' + index + ']').addClass('select');\r\n");
      out.write("\t\t$('.control_button[idx!=' + index + ']').removeClass('select');\r\n");
      out.write("\t\t$('.slider_text[idx=' + index + ']').show().animate({\r\n");
      out.write("\t\t\tleft : 0\r\n");
      out.write("\t\t}, 'slow');\r\n");
      out.write("\t\t$('.slider_text[idx!=' + index + ']').hide('slow', function() {\r\n");
      out.write("\t\t\t$(this).css('left', -300);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Product Catagories Area Start -->\r\n");
      out.write("\t<div class=\"products-catagories-area clearfix\">\r\n");
      out.write("\t\t<div class=\"animation_canvas\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"slider_panel\">\r\n");
      out.write("\t\t\t\t<img src=\"../slide/C1.png\" class=\"slider_image\" /> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"../slide/C2.jpg\" class=\"slider_image\" /> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"../slide/C3.png\" class=\"slider_image\" /> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"../slide/C4.jpg\" class=\"slider_image\" /> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"../slide/C5.jpg\" class=\"slider_image\" />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"control_panel\">\r\n");
      out.write("\t\t\t\t<div class=\"control_button\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"control_button\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"control_button\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"control_button\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"control_button\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"amado-pro-catagory clearfix\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>180,000</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>방송용 의자</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>24,000</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>공기정화용 꽃</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>18,000</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>의자</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>18,000</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>스탠드</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>18,000</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>화분</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>320,000</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>테이블</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/7.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>31,800</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>메탈릭 의자</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/8.jpg\" alt=\"\"> <!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>31,800</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>예쁜 의자</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Single Catagory -->\r\n");
      out.write("\t\t\t<div class=\"single-products-catagory clearfix\">\r\n");
      out.write("\t\t\t\t<a href=\"shop.html\"> <img src=\"../img/bg-img/9.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t<!-- Hover Content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"hover-content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"line\"></div>\r\n");
      out.write("\t\t\t\t\t\t<p>31,000</p>\r\n");
      out.write("\t\t\t\t\t\t<h4>장식</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Product Catagories Area End -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
